# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/ekicam2/Projects/wrestling game/make"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/ekicam2/Projects/wrestling game/make"

# Include any dependencies generated for this target.
include CMakeFiles/../Game.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../Game.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../Game.dir/flags.make

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o: CMakeFiles/../Game.dir/flags.make
CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o: /home/ekicam2/Projects/wrestling\ game/main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/ekicam2/Projects/wrestling game/make/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o -c "/home/ekicam2/Projects/wrestling game/main.cpp"

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/ekicam2/Projects/wrestling game/main.cpp" > CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.i

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/ekicam2/Projects/wrestling game/main.cpp" -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.s

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.requires:

.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.requires

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.provides: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.requires
	$(MAKE) -f CMakeFiles/../Game.dir/build.make CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.provides.build
.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.provides

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.provides.build: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o


CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o: CMakeFiles/../Game.dir/flags.make
CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o: /home/ekicam2/Projects/wrestling\ game/Menu.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/ekicam2/Projects/wrestling game/make/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o -c "/home/ekicam2/Projects/wrestling game/Menu.cpp"

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/ekicam2/Projects/wrestling game/Menu.cpp" > CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.i

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/ekicam2/Projects/wrestling game/Menu.cpp" -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.s

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.requires:

.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.requires

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.provides: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.requires
	$(MAKE) -f CMakeFiles/../Game.dir/build.make CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.provides.build
.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.provides

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.provides.build: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o


CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o: CMakeFiles/../Game.dir/flags.make
CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o: /home/ekicam2/Projects/wrestling\ game/Level.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/ekicam2/Projects/wrestling game/make/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o -c "/home/ekicam2/Projects/wrestling game/Level.cpp"

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/ekicam2/Projects/wrestling game/Level.cpp" > CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.i

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/ekicam2/Projects/wrestling game/Level.cpp" -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.s

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.requires:

.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.requires

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.provides: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.requires
	$(MAKE) -f CMakeFiles/../Game.dir/build.make CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.provides.build
.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.provides

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.provides.build: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o


CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o: CMakeFiles/../Game.dir/flags.make
CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o: /home/ekicam2/Projects/wrestling\ game/Player.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/ekicam2/Projects/wrestling game/make/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o -c "/home/ekicam2/Projects/wrestling game/Player.cpp"

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/ekicam2/Projects/wrestling game/Player.cpp" > CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.i

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/ekicam2/Projects/wrestling game/Player.cpp" -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.s

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.requires:

.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.requires

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.provides: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.requires
	$(MAKE) -f CMakeFiles/../Game.dir/build.make CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.provides.build
.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.provides

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.provides.build: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o


CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o: CMakeFiles/../Game.dir/flags.make
CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o: /home/ekicam2/Projects/wrestling\ game/Animation.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/ekicam2/Projects/wrestling game/make/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o -c "/home/ekicam2/Projects/wrestling game/Animation.cpp"

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/home/ekicam2/Projects/wrestling game/Animation.cpp" > CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.i

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/home/ekicam2/Projects/wrestling game/Animation.cpp" -o CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.s

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.requires:

.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.requires

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.provides: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.requires
	$(MAKE) -f CMakeFiles/../Game.dir/build.make CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.provides.build
.PHONY : CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.provides

CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.provides.build: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o


# Object files for target ../Game
__/Game_OBJECTS = \
"CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o" \
"CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o" \
"CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o" \
"CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o" \
"CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o"

# External object files for target ../Game
__/Game_EXTERNAL_OBJECTS =

../Game: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o
../Game: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o
../Game: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o
../Game: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o
../Game: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o
../Game: CMakeFiles/../Game.dir/build.make
../Game: CMakeFiles/../Game.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="/home/ekicam2/Projects/wrestling game/make/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_6) "Linking CXX executable ../Game"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../Game.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../Game.dir/build: ../Game

.PHONY : CMakeFiles/../Game.dir/build

CMakeFiles/../Game.dir/requires: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/main.cpp.o.requires
CMakeFiles/../Game.dir/requires: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Menu.cpp.o.requires
CMakeFiles/../Game.dir/requires: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Level.cpp.o.requires
CMakeFiles/../Game.dir/requires: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Player.cpp.o.requires
CMakeFiles/../Game.dir/requires: CMakeFiles/../Game.dir/home/ekicam2/Projects/wrestling_game/Animation.cpp.o.requires

.PHONY : CMakeFiles/../Game.dir/requires

CMakeFiles/../Game.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../Game.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../Game.dir/clean

CMakeFiles/../Game.dir/depend:
	cd "/home/ekicam2/Projects/wrestling game/make" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/ekicam2/Projects/wrestling game/make" "/home/ekicam2/Projects/wrestling game/make" "/home/ekicam2/Projects/wrestling game/make" "/home/ekicam2/Projects/wrestling game/make" "/home/ekicam2/Projects/wrestling game/make/Game.dir/DependInfo.cmake" --color=$(COLOR)
.PHONY : CMakeFiles/../Game.dir/depend

